import type { Metadata } from 'next'
import React, { Suspense } from 'react'
import Loading from './loading'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children: React.ReactNode,
  // analytics: React.ReactNode,
  // team: React.ReactNode,
  modal: React.ReactNode,
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>
        <Suspense fallback={<Loading />}>
        <Link className={'text-4xl text-green-300'} href={"/"}>
          RootLayout<br />
        </Link><br />
        {props.analytics}
        {props.team}
        </Suspense>
      </body> */}
      {props.children}
        {props.modal}
    </html>
  )
}
